# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('link', models.CharField(max_length=250, null=True, verbose_name='项目链接')),
                ('description', models.TextField(null=True, verbose_name='项目说明')),
                ('pv', models.IntegerField(default=0, null=True, verbose_name='浏览量')),
                ('comments', models.IntegerField(default=0, null=True, verbose_name='评论人数')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
    ]
