# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 13:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Collect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='发布人'),
        ),
        migrations.AddField(
            model_name='collect',
            name='comments',
            field=models.IntegerField(default=0, null=True, verbose_name='评论人数'),
        ),
        migrations.AddField(
            model_name='collect',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='collect',
            name='description',
            field=models.TextField(null=True, verbose_name='项目说明'),
        ),
        migrations.AddField(
            model_name='collect',
            name='link',
            field=models.CharField(max_length=250, null=True, verbose_name='项目链接'),
        ),
        migrations.AddField(
            model_name='collect',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='发布时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collect',
            name='pv',
            field=models.IntegerField(default=0, null=True, verbose_name='浏览量'),
        ),
        migrations.AddField(
            model_name='collect',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=120, verbose_name='标题'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collect',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
