# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 12:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_type', models.CharField(max_length=10, verbose_name='评论对象')),
                ('reply_content', models.TextField(verbose_name='评论内容')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('is_active', models.CharField(choices=[('deleted', '已删除'), ('active', '正常')], default='active', max_length=10, verbose_name='评论状态')),
                ('reply_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='我的评论')),
                ('user_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented', to=settings.AUTH_USER_MODEL, verbose_name='被评论人')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
    ]
