# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='obj_id',
            field=models.IntegerField(null=True, verbose_name='评论对象ID'),
        ),
    ]
