# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 04:19
from __future__ import unicode_literals

import Blog.models
import Collect.models
import FAQuestion.models
import Usercenter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0002_comment_obj_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='obj_type',
            field=models.CharField(choices=[('user', Usercenter.models.User), ('blog', Blog.models.BlogPost), ('collect', Collect.models.Collect), ('question', FAQuestion.models.FAQuestion)], default='blog', max_length=10, verbose_name='评论对象'),
        ),
    ]
